---
title: "penguins_assignment"
candidate ID: '1053835'
date: "2022-12-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 4: Run a statistical test on the Palmer Penguins dataset and produce a figure to explain it.
```{r Question 4 Cleaning data, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
#Setting working directory
setwd("~/PenguinProjectAssignment")

#Loading packages using libraries function
source("functions/libraries.R")

#Loading the raw data
penguins_raw <- read.csv("data_raw/penguins_raw.csv")

#Looking at the raw data
head(penguins_raw)

#Sourcing cleaning function to clean the raw data
source("functions/cleaning.R")

#Cleaning the raw data
penguins_clean <- cleaning(penguins_raw)

#Looking at the clean data
head(penguins_clean)

#Saving the clean data
write.csv(penguins_clean, "data_clean/penguins_clean_2.csv")

#Reading in the clean data
penguins_now_clean <- read.csv("data_clean/penguins_clean_2.csv")

#Sourcing function for removing NAs from flipper length column
source("functions/remove_NAs_from_flipper_length.R")

#Removing NAs from flipper length column
penguins_flipper_vs_body_mass <- remove_NAs_from_flipper_length(penguins_now_clean)

#Viewing new data frame
head(penguins_flipper_vs_body_mass)
```

```{r Question 4 Fitting linear model, echo = FALSE}
#Fitting a linear model to analyse the relationship between body mass and flipper length
LinearModel <- lm(flipper_length_mm ~ body_mass_g, penguins_flipper_vs_body_mass)

#Looking at the results of the linear model
summary(LinearModel)
```

```{r Question 4 Plotting figure, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
#Sourcing function for making a plot of the linear model
source("functions/plot_flipper_vs_body_mass_figure.R")

#Creating figure
LinearModelplot <- plot_flipper_vs_body_mass_figure(penguins_flipper_vs_body_mass)

#Viewing figure
LinearModelplot

#Sourcing function for saving figure
source("functions/save_plot_svg.R")

#Saving figure
save_plot_svg(penguins_flipper_vs_body_mass, 
                      "figures/fig01_vector.svg", 
                      size = 14, scaling = 0.93)
```

